### ISSUE TITLE
Flask request being blocked in passive

### ISSUE THREAD

**Issue by jjackevans** [zecure/shadowd#74]
Hi,

I'm having the following issue using Shadowd on my Flask web-server.

GET requests are performing fine, but when creating a POST request with an XML body/content it is throwing this error in the logfile. I am using a profile on passive mode with only backlisting enabled.

Any help would be really appreciated!

```
TypeError: Object of type 'bytes' is not JSON serializable
2021-11-12 05:43:37	Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/shadowd/connector.py", line 270, in start
    config.get('ssl')
  File "/usr/local/lib/python3.6/site-packages/shadowd/connector.py", line 192, in send
    json_data = json.dumps(input_data)
  File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
 ```

**Connectors.ini:**
```
[shadowd_python]
profile=1
key=##
debug=1
log=/var/log/shadowd.log
```

**app.py**
```
from shadowd.flask_connector import InputFlask, OutputFlask, Connector

app = Flask(__name__)


# Hook for Shadowd - comment out to test without WAF
@app.before_request
def before_req():
    input = InputFlask(request)
    output = OutputFlask()
    Connector().start(input, output)
```

**Comment by zit-hb** [comment]
Hi @jjackevans,

thanks for the report! It seems to be regression caused by newer versions. I plan to give the Python connector some love soon, then I will fix it.
