### ISSUE TITLE
Corrupted File: A required file to initialize the web application firewall is corrupted and can not be parsed.

### ISSUE THREAD

**Issue by TylerByte666** [zecure/shadowd#91]
Good day, thank you for the wonderful work! 😍  

I have followed the official steps for installing shadowd and a php connector for a nginx webserver running a Yii2 app on CentOS 7.

The web interface is up and I have made a profile for the app.

I have added the nginx conf:
```conf
 fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/php/shadowd.php";
```
After web server restart, I now get an error when visiting the yii2 application in the browser:
 ```debug
 Shadow Daemon
Corrupted File

A required file to initialize the [Shadow Daemon](https://shadowd.zecure.org/) web application firewall is corrupted and can not be parsed.

Enable the debug setting to get additional information about the corrupted file.
```

I have shadowd on the same machine as the app and its nginx web server... could it be a docker networking issue or am I being silly? I have made sure the permissions were given to nginx user and also tried installing the connector in the `/var/www/html/` directory.

Upon further investigation my logs reveled this error:
```
2022/08/15 13:39:30 [error] 9759#9759: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  syntax error, unexpected '!' in /etc/shadowd/connectors.ini on line 6
```

Please help me 😢

**Comment by TylerByte666** [comment]
So upon further testing it was the key I was using. So i changed it, but now I get the following error:

```
Processing Error

The connector received a response from the [Shadow Daemon](https://shadowd.zecure.org/) server that could not be parsed.

A wrong address (host/port) might be specified in the configuration file of the [connector](https://shadowd.zecure.org/documentation/connectors/).
shadowd\Exceptions\ProcessingException

#0 /usr/share/shadowd/php/src/Connection.php(74): shadowd\Connection->parseOutputData('')
#1 /usr/share/shadowd/php/src/Connector.php(55): shadowd\Connection->send(Object(shadowd\Input))
#2 /usr/share/shadowd/php/shadowd.php(26): shadowd\Connector->start()
#3 {main}

You are seeing this stack trace because the debug mode is enabled. Debug output might leak information and should be disabled when not needed.
```

But it is up and running and I can get to the ui. Here is my config `/etc/shadowd/connectors.ini `:

```
[shadowd_php]
; Sets the profile id. Required.
profile=1

; Sets the key for the profile. Required.
key=12345

; Sets the address of the shadowd server.
; Default Value: 127.0.0.1
;host=127.0.0.1

; Sets the port of the shadowd server.
; Default Value: 9115
;port=9115

; Sets the connection timeout (in seconds).
; Default Value: 5
;timeout=

; Sets the path to the public key and enables SSL. It requires enabled SSL in
; shadowd, otherwise the connection will fail.
;ssl=

; If activated threats are not removed. This can be used to test new rules without
; making the web application unusable. It can be also used to turn Shadow Daemon
; into a high-interaction web honeypot.
; Possible Values:
;   0
;   1
; Default Value: 0
;observe=

; If activated the templating system will print proper error messages instead of a
; generic error.
; Possible Values:
;   0
;   1
; Default Value: 1
;templates=

; If activated log messages are send to the web server and saved in the log file.
; Additionally, stack traces for exceptions are shown in the templates.
; Possible Values:
;   0
;   1
; Default Value: 0
debug=1

; If set the ignore list is used to ignore certain parameters and not send them to
; the shadowd server. It is good practise to not send passwords or other very
; sensitive information to the server.
;ignore=

; If activated raw post data is saved as user input. The raw data is hard to analyze,
; but can be a source for malicious input as well.
; Possible Values:
;   0
;   1
; Default Value: 0
;raw_data=

; Sets the source for the client ip. It is used as key of $_SERVER. If you are using a
; reverse proxy or something similar forward the real client ip and reference it
; here, e.g., HTTP_X_FORWARDED_FOR.
; Default Value: REMOTE_ADDR
;client_ip=

; Sets the source for the caller. It is used as key of $_SERVER. The caller should
; represent the resource. Usually, that is the case when using the executed script. It is
; not the case if you are routing all requests through one script though. In that case use
; PHP_SELF, REDIRECT_URL, or similar sources to differentiate the different routes.
; Default Value: SCRIPT_FILENAME
;caller=

; Sets the source for the resource identifier. It is a key of $_SERVER.
; Default Value: REQUEST_URI
;resource=
```

Please help??

**Comment by zit-hb** [comment]
Hey @TylerByte666 ,

is your web application also running in a Docker container by any chance? If not, can you try to connect to shadowd with NetCat? The command would be `nc -v 127.0.0.1 9115`.

**Comment by TylerByte666** [comment]
Hey! Thank you for your reply.

1. No the Yii app is running on an nginx server on the same host as the docker and the shadowd installation.

2. The netcat was able to connect, Ui is up and running when I head to 127.0.0.1:8080:

```
[root@localhost shadowdctl]# nc -v 127.0.0.1 9115
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:9115.
```

When I head to the backend url of the app I still get the Processing Error above... Should I perhaps have it on a different stand-alone server?

**Comment by zit-hb** [comment]
I am not seeing the reason for the problem.

I would look into the shadowd logs, maybe that contains a relevant information. It might help to activate verbose logging by removing the `#` [here](https://github.com/zecure/shadowdctl/blob/v2.0.0/docker-compose.yml#L40). You get the logs by running `./shadowdctl logs shadowd`.

**Comment by TylerByte666** [comment]
Thank you I changed the docker-compose file and started the shadowdctl image again.
All I get in the output is the running of that command we uncommented:

```
[root@localhost shadowdctl]# ./shadowdctl logs shadowd
Attaching to shadowdctl_shadowd_1
shadowd_1  | Starting command /usr/bin/shadowd -c /etc/shadowd/shadowd.ini -U shadowd -G shadowd --verbose
```

What is weird is I nc the CentOS host and I get:
```
[root@localhost shadowdctl]# nc -v 127.0.0.1 9115
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:9115.
```

but the funny thing is, I installed it on another server running Ubuntu 22.04 LTS
and I tried the nc command there I got this:
```
root@localhost:~# nc -v 127.0.0.1 9115
Connection to 127.0.0.1 9115 port [tcp/*] succeeded!
```

which is very different from the CentOS output... could this be the issue?

**Comment by zit-hb** [comment]
Great, glad you got it working!
